# @package model
_target_: models.smart.smart.SMART
spatial_dim: 2
parameter_channels: 2
latent_dim: 128
latent_geometry_points: 128
subsampled_geometry_points: 256
num_encoder_decoder_blocks: 4
num_heads: 8
pos_scale_factor: 1000.0
dropout: 0.05
subregion_size: 1000
